### ISSUE TITLE
Llama-2 models need authentication

### ISSUE THREAD

**Issue by ChrisPalmerNZ** [Data-drone/ANZ_LLM_Bootcamp#7]
Can you please add the capacity to pass in the current user's Hugging Face token to the `use_auth_token` parameter during the initialization of tokenizer, model_config, and model in the 0.1_Huggins_Face_basics, Utils, etc. notebooks? It is required to download the model from the Meta website via Hugging Face.

**Comment by Data-drone** [comment]
HF Models can now be preloaded via setting up a token with db_secrets and running the lab_setup notebook
